name: sortchest
main: io.github.doctorluk.sortchest.sortchest
version: 0.1
commands:
#   killradius:
#      description: Kills specified animals within a specified radius
#      usage: /killradius <animaltype> [radius]
#      permission: firstplugin.killradius
#      permission-message: You don't have <permission>
   sortchest:
      description: Swaps the contents of two left-clicked chests
      usage: /sortchest
      permission: sortchest.sort
      permission-message: You don't have <permission>