name: swapchests
main: io.github.doctorluk.swapchests.swapchests
version: 0.1
commands:
#   killradius:
#      description: Kills specified animals within a specified radius
#      usage: /killradius <animaltype> [radius]
#      permission: firstplugin.killradius
#      permission-message: You don't have <permission>
   swapchests:
      description: Swaps the contents of two left-clicked chests
      usage: /swapchests
      permission: swapchests.swap
      permission-message: You don't have <permission>